import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const root='./';const source=fs.readFileSync(root+'worker.js','utf8').replace("import initial from './initial.json';",'const initial='+fs.readFileSync(root+'initial.json','utf8')+';');const {default:worker,LoginGuard}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const objects=new Map();const namespace={idFromName:name=>name,get(name){if(!objects.has(name)){const map=new Map();let queue=Promise.resolve();const storage={async get(k){return structuredClone(map.get(k))},async put(k,v){map.set(k,structuredClone(v))},async delete(k){map.delete(k)},async setAlarm(t){this.alarmTime=t},async deleteAlarm(){this.alarmTime=null},transaction(fn){const task=queue.then(()=>fn(this));queue=task.catch(()=>{});return task}};objects.set(name,new LoginGuard({storage}));}return objects.get(name)}};
const kv=new Map();const env={ADMIN_USERNAME:'root',ADMIN_PASSWORD:'test-password',LOGIN_GUARD:namespace,DATA:{async get(k){return kv.has(k)?JSON.parse(kv.get(k)):null},async put(k,v){kv.set(k,v)}},ASSETS:{async fetch(req){const file=new URL(req.url).pathname.slice(1);return new Response(fs.readFileSync(root+'public/'+file,'utf8'))}}};
const request=async(path,{body,user='root',password='test-password',origin='https://test.local',ip='203.0.113.22',headers={}}={})=>{const req=new Request('https://test.local'+path,{method:body?'POST':'GET',headers:{Origin:origin,'CF-Connecting-IP':ip,'X-Admin-User':user,Authorization:'Bearer '+password,'Content-Type':'application/json','User-Agent':'Mozilla/5.0 (iPhone) AppleWebKit Safari/604.1',...headers},...(body?{body:JSON.stringify(body)}:{})});Object.defineProperty(req,'cf',{value:{country:'US'}});return worker.fetch(req,env)};
assert.equal((await request('/visit-event',{body:{consent:false,event:'web'}})).status,400);assert.equal((await request('/visit-event',{origin:'https://other.local',body:{consent:true,event:'web'}})).status,403);
assert.equal((await request('/visit-event',{body:{consent:true,event:'web'}})).status,200);await request('/visit-event',{body:{consent:true,event:'web'}});
let response=await request('/api/visits');let data=await response.json();assert.equal(data.records.length,1);assert.equal(data.records[0].ip,'203.0.113.22');assert.equal(data.records[0].country,'US');assert.equal(data.records[0].browser,'Safari');assert.equal(data.records[0].device,'Móvil');assert.equal(data.retentionDays,7);
await request('/visit-event',{body:{consent:true,event:'app'}});await request('/visit-event',{body:{consent:true,event:'installed'}});data=await (await request('/api/visits')).json();assert.equal(data.records.length,3);
assert.equal((await request('/api/visits',{password:'wrong',ip:'203.0.113.44'})).status,401);
await request('/api/users',{body:{username:'editor1',password:'LongPassword123!',role:'editor'}});assert.equal((await request('/api/visits',{user:'editor1',password:'LongPassword123!',ip:'203.0.113.55'})).status,403);
const store=objects.get('private-visits-v1');assert(store.state.storage.alarmTime>Date.now());const originalNow=Date.now;Date.now=()=>originalNow()+7*24*60*60*1000+1000;await store.alarm();assert.equal((await (await request('/api/visits')).json()).records.length,0);assert.equal(store.state.storage.alarmTime,null);Date.now=originalNow;
await request('/visit-event',{body:{consent:true,event:'web'}});await request('/api/visits',{body:{action:'clear'}});assert.equal((await (await request('/api/visits')).json()).records.length,0);
for(const name of ['admin.html','template.html'])for(const m of fs.readFileSync(root+'public/'+name,'utf8').matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);
const publicHTML=await (await request('/')).text();assert(publicHTML.includes('Continuar sin registro'));assert(!publicHTML.includes('203.0.113.22'));assert(publicHTML.includes('visit-privacy'));assert(publicHTML.includes('Noticias'));
console.log('OK: consent required, origin validation, server IP/client parsing, deduplication, app events, authenticated admin only, automatic expiry and manual clear, public privacy without exposing IPs, UI syntax.');

await Promise.all(Array.from({length:20},()=>request('/visit-event',{body:{consent:true,event:'web'},ip:'198.51.100.1'})));assert.equal((await (await request('/api/visits')).json()).records.length,1);
for(let i=0;i<1005;i++)await store.fetch(new Request('https://guard/visits',{method:'POST',body:JSON.stringify({action:'record',record:{ip:'2001:db8:'+i,event:'web',country:'US',browser:'Chrome',device:'Ordenador / otro'}})}));let retained=await (await store.fetch(new Request('https://guard/visits',{method:'POST',body:JSON.stringify({action:'list'})}))).json();assert.equal(retained.records.length,1000);for(const key of ['visits-a','visits-b'])assert(Buffer.byteLength(JSON.stringify(await store.state.storage.get(key)))<128*1024);console.log('OK: concurrent duplicate requests and 1,000-record cap within storage value limits.');
